# frontend/Dockerfile.dev
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Vite uses a different port and host setting
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]